# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bot/v1/policy.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'bot/v1/policy.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x62ot/v1/policy.proto\x12\x06\x62ot.v1\"w\n\x06Policy\x12\x10\n\x08obs_size\x18\x01 \x01(\r\x12\x14\n\x0c\x61\x63tion_count\x18\x02 \x01(\r\x12&\n\nactivation\x18\x03 \x01(\x0e\x32\x12.bot.v1.Activation\x12\x1d\n\x06layers\x18\x04 \x03(\x0b\x32\r.bot.v1.Layer\"P\n\x05Layer\x12\x13\n\x0bin_features\x18\x01 \x01(\r\x12\x14\n\x0cout_features\x18\x02 \x01(\r\x12\x0e\n\x06weight\x18\x03 \x03(\x02\x12\x0c\n\x04\x62ias\x18\x04 \x03(\x02*=\n\nActivation\x12\x1a\n\x16\x41\x43TIVATION_UNSPECIFIED\x10\x00\x12\x13\n\x0f\x41\x43TIVATION_TANH\x10\x01\x42:Z8github.com/alcares/mmoserver/backend/gen/go/bot/v1;botv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bot.v1.policy_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z8github.com/alcares/mmoserver/backend/gen/go/bot/v1;botv1'
  _globals['_ACTIVATION']._serialized_start=234
  _globals['_ACTIVATION']._serialized_end=295
  _globals['_POLICY']._serialized_start=31
  _globals['_POLICY']._serialized_end=150
  _globals['_LAYER']._serialized_start=152
  _globals['_LAYER']._serialized_end=232
# @@protoc_insertion_point(module_scope)
