# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sim/v1/env.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'sim/v1/env.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10sim/v1/env.proto\x12\x06sim.v1\"\"\n\x0bObservation\x12\x13\n\x0bobservation\x18\x01 \x03(\x02\"\x1d\n\x0cResetRequest\x12\r\n\x05seeds\x18\x01 \x03(\x03\"L\n\rResetResponse\x12)\n\x0cobservations\x18\x01 \x03(\x0b\x32\x13.sim.v1.Observation\x12\x10\n\x08obs_size\x18\x02 \x01(\r\"\x1e\n\x0bStepRequest\x12\x0f\n\x07\x61\x63tions\x18\x01 \x03(\x05\"\xa2\x01\n\x0cStepResponse\x12)\n\x0cobservations\x18\x01 \x03(\x0b\x32\x13.sim.v1.Observation\x12\x0f\n\x07rewards\x18\x02 \x03(\x02\x12\x12\n\nterminated\x18\x03 \x03(\x08\x12\x11\n\ttruncated\x18\x04 \x03(\x08\x12/\n\x12\x66inal_observations\x18\x05 \x03(\x0b\x32\x13.sim.v1.Observation2n\n\x03\x45nv\x12\x34\n\x05Reset\x12\x14.sim.v1.ResetRequest\x1a\x15.sim.v1.ResetResponse\x12\x31\n\x04Step\x12\x13.sim.v1.StepRequest\x1a\x14.sim.v1.StepResponseB:Z8github.com/alcares/mmoserver/backend/gen/go/sim/v1;simv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sim.v1.env_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z8github.com/alcares/mmoserver/backend/gen/go/sim/v1;simv1'
  _globals['_OBSERVATION']._serialized_start=28
  _globals['_OBSERVATION']._serialized_end=62
  _globals['_RESETREQUEST']._serialized_start=64
  _globals['_RESETREQUEST']._serialized_end=93
  _globals['_RESETRESPONSE']._serialized_start=95
  _globals['_RESETRESPONSE']._serialized_end=171
  _globals['_STEPREQUEST']._serialized_start=173
  _globals['_STEPREQUEST']._serialized_end=203
  _globals['_STEPRESPONSE']._serialized_start=206
  _globals['_STEPRESPONSE']._serialized_end=368
  _globals['_ENV']._serialized_start=370
  _globals['_ENV']._serialized_end=480
# @@protoc_insertion_point(module_scope)
